name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [8.0]
        dependency-version: [prefer-lowest, prefer-stable]
    name: P${{ matrix.php-versions }} - ${{ matrix.dependency-version }} - ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: action/checkout@v1

      - name: Cache dependencies
        uses: action/checkout@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php-versions }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: opcache, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependecies
        run: composer update --${{ metrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit

